Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -9,7 +9,12 @@ jobs:
     steps:
       - name: Failing task
         run: |
-          bash -c "echo subshell; false; echo $?; exit 0"
+          bash -c "\
+            echo 'in subshell'; \
+            false; \
+            echo 'capture error here:' $?; \
+            exit 0; \
+          "
                     
           echo "main exit code: $?"
           exit 0
